AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Simple SAM application that creates an API gateway, with an endpoint mapped to a Lambda function that calls a state machine which runs two other Lambda functions in parallel.

Globals:
  Function:
    CodeUri: src/
    Runtime: nodejs18.x
    Architectures: ["arm64"]

Resources:
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler1

  Function2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler2

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: CallFunctionsInParallel
        States:
          CallFunctionsInParallel:
            Type: Parallel
            End: true
            Branches:
              - StartAt: CallFunction1
                States:
                  CallFunction1:
                    Type: Task
                    Resource: !GetAtt Function1.Arn
                    End: true
              - StartAt: CallFunction2
                States:
                  CallFunction2:
                    Type: Task
                    Resource: !GetAtt Function2.Arn
                    End: true
      Type: EXPRESS
      Tracing:
        Enabled: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref Function1
        - LambdaInvokePolicy:
            FunctionName: !Ref Function2

  HttpApi:
    Type: AWS::Serverless::HttpApi

  StateMachineCaller:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Environment:
        Variables:
          STATE_MACHINE_ARN: !GetAtt StateMachine.Arn
      Events:
        HttpApiGateway:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /sm
            Method: get
      Policies:
        - Version: 2012-10-17
          Statement:
            Effect: Allow
            Action: ["states:StartSyncExecution"]
            Resource: !GetAtt StateMachine.Arn

Outputs:
  HttpApiEndpoint:
    Description: "HTTP API endpoint"
    Value: !GetAtt HttpApi.ApiEndpoint
