AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple SAM application that creates an API gateway, with an endpoint mapped to a Lambda function that calls a state machine which runs two other Lambda functions in parallel.

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine.asl.yml
      Type: EXPRESS
      Tracing:
        Enabled: true
      DefinitionSubstitutions:
        Function1: !GetAtt Function1.Arn
        Function2: !GetAtt Function2.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref Function1
        - LambdaInvokePolicy:
            FunctionName: !Ref Function2

  Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/function1/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/function2/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  StateMachineCaller:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/state-machine-caller/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          STATE_MACHINE_ARN: !GetAtt StateMachine.Arn
      Events:
        HttpApiGateway:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /sm
            Method: get
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - states:StartSyncExecution
              Resource: !GetAtt StateMachine.Arn

Outputs:
  HttpApiEndpoint:
    Description: "HTTP API endpoint"
    Value: !GetAtt HttpApi.ApiEndpoint
