AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A Lambda function that is executed on a schedule using an EventBridge rule

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures: ["arm64"]
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
