AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures: ['arm64']
      Events:
        IotRuleEvent:
          Type: IoTRule
          Properties:
            Sql: SELECT * from 'topic/test'
